version: '3.7'
services:

  gitea:
    image: alpine:3.21
    environment:
      MYSQL_DB_HOST: mysql:3306
    ports: ["3000:3000"]
    volumes:
      - type: bind
        source: ./gitea-startup.sh
        target: /gitea-startup.sh
      - data:/data
    command: ["/bin/sh", "-c", "/gitea-startup.sh"]
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
    ports: ["3306:3306"]

volumes:
    data: {}
